"""RetrievalQA knowledge Q&A chain backed by an in-memory Chroma vector store.

The module-level ``_qa_chain`` instance is created once at import time.  It
loads documents from ``tests/fixtures/sample_docs.md``, splits them into
chunks, embeds them via ZhipuAI ``embedding-3``, and stores the vectors in
an in-memory Chroma collection.  Unit tests mock
``src.chains.qa_chain._qa_chain.run`` to avoid real LLM/embedding calls.

Implementation note
-------------------
RetrievalQA (langchain 0.3.x) is a Pydantic v2 model, just like LLMChain.
Pydantic v2 models forbid arbitrary attribute assignment/deletion, which means
``mocker.patch("...._qa_chain.run", ...)`` would fail when pytest-mock tries
to restore the original value via ``delattr``.

The same ``_ChainWrapper`` pattern used in ``intent_classifier.py`` is applied
here: the RetrievalQA instance is wrapped in a plain Python object whose
``run`` method can be freely patched by pytest-mock.
"""

import os
import pathlib

from dotenv import load_dotenv
from langchain.chains import RetrievalQA
from langchain.schema import BaseRetriever
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain_community.vectorstores import Chroma
from langchain_openai import OpenAIEmbeddings

from src.config import get_llm

load_dotenv()

# ---------------------------------------------------------------------------
# Embeddings model (ZhipuAI embedding-3, OpenAI-compatible)
# ---------------------------------------------------------------------------

_embeddings = OpenAIEmbeddings(
    model="embedding-3",
    openai_api_key=os.getenv("ZHIPU_API_KEY"),
    openai_api_base="https://open.bigmodel.cn/api/paas/v4/",
)

# ---------------------------------------------------------------------------
# Public API: build_retriever
# ---------------------------------------------------------------------------


def build_retriever(docs: list[str]) -> BaseRetriever:
    """Build an in-memory Chroma retriever from a list of plain-text strings.

    Args:
        docs: A list of plain-text document strings to index.

    Returns:
        A Chroma-backed retriever configured to return the top-3 matches (k=3).
    """
    splitter = RecursiveCharacterTextSplitter(chunk_size=500, chunk_overlap=50)
    chunks: list[str] = []
    for doc in docs:
        chunks.extend(splitter.split_text(doc))

    vectorstore = Chroma.from_texts(
        texts=chunks,
        embedding=_embeddings,
    )
    return vectorstore.as_retriever(search_kwargs={"k": 3})


# ---------------------------------------------------------------------------
# Wrapper — makes _qa_chain.run freely patchable by pytest-mock
# ---------------------------------------------------------------------------


class _ChainWrapper:
    """Thin wrapper around RetrievalQA to allow attribute-level mocking.

    RetrievalQA is a Pydantic v2 BaseModel with ``model_config`` that
    prevents ``setattr``/``delattr`` on arbitrary attributes.  By delegating
    through this plain Python class, ``mocker.patch("...._qa_chain.run", ...)``
    works without restriction.
    """

    def __init__(self, retrieval_qa: RetrievalQA) -> None:
        self._retrieval_qa = retrieval_qa

    def run(self, query: str) -> str:
        """Invoke the underlying RetrievalQA chain and return its string output."""
        return self._retrieval_qa.run(query)


# ---------------------------------------------------------------------------
# Module-level chain initialisation
# ---------------------------------------------------------------------------

def _load_sample_docs() -> list[str]:
    """Load the sample_docs.md fixture as a list of text chunks.

    The fixture path is resolved relative to this file's location so that the
    module works regardless of the current working directory.
    """
    fixture_path = (
        pathlib.Path(__file__).parent.parent.parent
        / "tests"
        / "fixtures"
        / "sample_docs.md"
    )
    text = fixture_path.read_text(encoding="utf-8")
    return [text]


_retriever = build_retriever(_load_sample_docs())

_qa_chain = _ChainWrapper(
    RetrievalQA.from_chain_type(
        llm=get_llm(),
        chain_type="stuff",
        retriever=_retriever,
    )
)

# ---------------------------------------------------------------------------
# Public API: answer_question
# ---------------------------------------------------------------------------


def answer_question(question: str) -> str:
    """Answer a question using the pre-built RetrievalQA chain.

    Args:
        question: The natural-language question from the user.

    Returns:
        A string answer generated by the LLM based on the retrieved context.
    """
    return _qa_chain.run(question)
